-- ═══════════════════════════════════════════════════════════════════════════
--  GO WATT — notification inbox
--
--  Until now push was fire-and-forget (integrations/push.ts → Expo, nothing
--  stored), so there was no history to show in the app. This table is the
--  durable record behind the in-app bell; push stays the transient delivery
--  channel and the two are written together by notify() in the backend.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  -- Coarse channel, mirrors the notif_* opt-out columns on profiles.
  category   text not null default 'booking',    -- booking | charging | promo
  -- Fine-grained event name; the app maps this to an icon/colour and the role
  -- filter uses it. e.g. booking_confirmed, charge_start_soon, payout_sent.
  kind       text not null,
  title      text not null,
  body       text not null,
  -- Free-form payload for deep-linking (booking_id, session_id, …).
  data       jsonb not null default '{}'::jsonb,
  -- Set once the user opens the inbox / taps the row.
  read_at    timestamptz,
  created_at timestamptz not null default now(),
  -- Reminders are generated by polling cron jobs that re-see the same booking
  -- every run. This key makes "one reminder per booking per kind" enforceable
  -- rather than relying on the job's timing window being exact. Null for
  -- ordinary event notifications, which are emitted once by definition.
  dedupe_key text
);

-- One row per dedupe_key. Partial so the unlimited nulls above are allowed.
create unique index if not exists uq_notifications_dedupe
  on public.notifications (dedupe_key)
  where dedupe_key is not null;

-- The inbox query: newest-first for one user.
create index if not exists idx_notifications_user_created
  on public.notifications (user_id, created_at desc);

-- The badge query. Partial keeps it tiny — only unread rows are indexed.
create index if not exists idx_notifications_unread
  on public.notifications (user_id)
  where read_at is null;

alter table public.notifications enable row level security;

-- Users read and update (mark-read) only their own. All inserts go through the
-- backend, which connects as postgres and bypasses RLS.
drop policy if exists "own notifications read" on public.notifications;
create policy "own notifications read" on public.notifications
  for select using (auth.uid() = user_id);

drop policy if exists "own notifications update" on public.notifications;
create policy "own notifications update" on public.notifications
  for update using (auth.uid() = user_id);
